Update README.md
shahednasser/awesome-resources pull request #302
Opened 2021-10-27 18:19 UTC by GuliaShubham

Added YouTube Java tutorials playlist link from one of the best institutes in India to learn coding.

2021-10-29 18:20 UTC, GuliaShubham commented
@shahednasser please have a look I just Made the changes.

2021-10-29 19:12 UTC, GuliaShubham commented
@shahednasser please take a look at the resources I have put on the list.

2021-10-29 20:41 UTC, shahednasser requested changes

2021-10-29 20:41 UTC, shahednasser commented on README.md
> +- [MySQL tutorial](https://www.youtube.com/watch?v=u96rVINbAUI&list=PLZlA0Gpn_vH9lZBruSHgs41ldy5gZgknU)
This does not qualify so please remove it

2021-10-29 20:41 UTC, shahednasser commented on README.md
> +- [Introduction to Node JS](https://www.youtube.com/watch?v=VShtPwEkDD0&list=PLZlA0Gpn_vH_uZs4vJMIhcinABSTUH2bY)
Change to the link of the playlist page

2021-10-29 20:41 UTC, shahednasser commented on README.md
> +- [Java Beginners to Pro Course](https://www.youtube.com/playlist?list=PL9gnSGHSqcnr_DxHsP7AW9ftq0AtAyYqJ)
Change the title to the title of the playlist

2021-10-30 18:19 UTC, GuliaShubham commented
@shahednasser Please check now. The git tutorial is a single video and not a playlist. I changed the title of the playlist and removed the one you asked for.

2021-10-31 10:40 UTC, shahednasser requested changes
I have a few last changes below. I'll also add the `hacktoberfest-accepted` label in case this PR doesn't get merged before the end of the day

2021-10-31 10:40 UTC, shahednasser commented on README.md
> +- [Java + DSA + Interview Preparation Course](https://www.youtube.com/playlist?list=PL9gnSGHSqcnr_DxHsP7AW9ftq0AtAyYqJ)
You need to add a new line below this.

2021-10-31 10:40 UTC, shahednasser commented on README.md
> +-
Remove the `-` here. it should be an empty line

2021-10-31 10:40 UTC, shahednasser commented on README.md
> +- [Introduction to Node.js](https://www.youtube.com/playlist?list=PLZlA0Gpn_vH_uZs4vJMIhcinABSTUH2bY)
Add a new empty line below this

2021-10-31 16:48 UTC, GuliaShubham commented
@shahednasser tried to resolve the problems please have a look.

2021-11-01 21:30 UTC, GuliaShubham commented
@shahednasser please have a look made some new commits and the previous is also changed.

2021-11-02 08:52 UTC, merged

2021-11-02 08:52 UTC, shahednasser commented
Great thanks!