Added C++ resources to help the community flourish
shahednasser/awesome-resources pull request #313
Opened 2021-10-29 19:54 UTC by rohitgarg025

Added C++ resources to help the community flourish

2021-10-29 20:45 UTC, shahednasser requested changes
Thank you for contributing @rohitgarg025 I have a few comments below.

2021-10-29 20:45 UTC, shahednasser commented on README.md
> +- [Reference for C++](https://www.cplusplus.com/reference/)
There's already a C++ section, however, it's misplaced after Express. Please move the resources to that section

2021-10-29 20:45 UTC, shahednasser commented on README.md
> +- [GFG C++ List](https://www.geeksforgeeks.org/c-plus-plus/)
This link is a duplicate so please remove it.

2021-10-29 20:45 UTC, shahednasser commented on README.md
> +- [Derek Banas Playlist](https://www.youtube.com/watch?v=DamuE8TM3xo&list=PLGLfVvz_LVvQ9S8YSV0iDsuEU8v11yP9M)
Change the link to the link of the playlist and make sure the title matches the name of the playlist

2021-10-30 01:26 UTC, rohitgarg025 commented
@shahednasser  please check my latest commit now. I have incorporated the desired changes. Thanks a lot for guiding.

2021-10-31 10:34 UTC, merged

2021-10-31 10:35 UTC, shahednasser commented
Great thanks!