Add TypeScript full course for beginners
shahednasser/awesome-resources pull request #316
Opened 2021-10-30 17:10 UTC by muhammadcaeed

Added a full course of TypeScript for beginners that covers the latest updates till 2021.

2021-10-31 10:38 UTC, shahednasser requested changes
Thank you @muhammadcaeed for your contribution. I have added one comment for you to fix. I have also added the `hacktoberfest-accepted` label in case this PR doesn't get merged before the end of today.

2021-10-31 10:38 UTC, shahednasser commented on README.md
> +- [TypeScript Course for Beginners 2021 - Learn TypeScript from Scratch!](https://www.youtube.com/watch?v=BwuLxPH8IDs&t=1s)
Please add a new empty line after this

2021-10-31 14:21 UTC, muhammadcaeed commented
@shahednasser  You might notice an extra commit for another section, but it's already reverted. I will add a new PR for it.

2021-11-02 08:50 UTC, merged

2021-11-02 08:50 UTC, shahednasser commented
Thank you!