Added Flask Tutorial under Python Category
shahednasser/awesome-resources pull request #326
Opened 2021-12-05 18:38 UTC by Lonercode

2021-12-06 17:43 UTC, shahednasser requested changes
Hello @Lonercode thank you for your contribution. I added a comment below

2021-12-06 17:43 UTC, shahednasser commented on README.md
> +- [Python Flask Tutorial](https://youtube.com/playlist?list=PLzMcBGfZo4-n4vJJybUVV3Un_NFS5EOgX)
Add a new line below this

2021-12-06 21:07 UTC, Lonercode commented on README.md
> +- [Python Flask Tutorial](https://youtube.com/playlist?list=PLzMcBGfZo4-n4vJJybUVV3Un_NFS5EOgX)
Alright.

2021-12-08 12:58 UTC, merged

2021-12-08 12:58 UTC, shahednasser commented
Great thanks!