Added frontend challenges websites
shahednasser/awesome-resources pull request #359
Opened 2022-02-03 07:20 UTC by naiiiden

2022-02-03 08:33 UTC, shahednasser requested changes
Thank you @naiiiden for your contribution. I've added some comments below.

2022-02-03 08:33 UTC, shahednasser commented on README.md
> +- :other: [Frontend Coding Challenges](https://www.frontendmentor.io)
Please change the title to the page's title

2022-02-03 08:33 UTC, shahednasser commented on README.md
> +- :other: [Frontend Coding Challenges](https://www.codewell.cc)
Please change the title to the page's title.

Also, please add a new empty line after this.

2022-02-04 08:23 UTC, shahednasser commented on README.md
> +- :bulb: [Codeell.cc Design To Code Frontend Challenges](https://www.codewell.cc)
Can you fix the typo in the name here?

2022-02-04 14:15 UTC, naiiiden commented on README.md
> +- :bulb: [Codeell.cc Design To Code Frontend Challenges](https://www.codewell.cc)
yes, check commit "fixed typo"

2022-02-05 15:57 UTC, merged

2022-02-05 15:57 UTC, shahednasser commented
Great thanks!