Added a new resource
shahednasser/awesome-resources pull request #393
Opened 2022-07-21 13:41 UTC by sandeepmishratech

Added a new resource under 'C'. This C Programming Tutorial is explained with real-world examples and provides hands-on experience for various coding problems. Hope this small contribution will help the learners.

2022-07-22 06:47 UTC, shahednasser commented on README.md
> +- :file_folder: [C Programming Tutorial](https://www.scaler.com/topics/c/)
Change the emoji to `:books:` and change the title to the same title as the page.

2022-07-22 14:33 UTC, sandeepmishratech commented
hi @shahednasser,

I have made all the changes, please check.

Thank You!

2022-07-24 15:57 UTC, shahednasser commented on README.md
> +- :books: [C Tutorial](https://www.scaler.com/topics/c/)
The title is longer than this as I can see when I open the page. Please set it to "C Tutorial - Learn C in Detail" and do the same for the other pages.

2022-07-27 16:36 UTC, sandeepmishratech commented
Hi @shahednasser,

I have made all the changes as suggested, please check.

Thank You!

2022-08-05 21:28 UTC, shahednasser requested changes

2022-08-05 21:28 UTC, shahednasser commented on README.md
> +- :books: [C Tutorial | Learn C in Detail](https://www.scaler.com/topics/c/)
change `|` to `-` and please do it everywhere you've used it.

2022-08-07 16:03 UTC, sandeepmishratech commented
Hi @shahednasser,

I have made the changes.

2022-08-10 21:43 UTC, merged

2022-08-10 21:43 UTC, shahednasser commented
Thanks!