Update README.md
shahednasser/awesome-resources pull request #408
Opened 2022-08-16 05:42 UTC by Aakrut

Added Typescript Tutorial Link at the Bottom of the "TypeScript" Category List.

2022-08-22 15:35 UTC, shahednasser requested changes

2022-08-22 15:35 UTC, shahednasser commented on README.md
> +- :green_book: [Learn TypeScript From Scratch](https://www.typescripttutorial.net/)
```suggestion
- :books: [Learn TypeScript From Scratch](https://www.typescripttutorial.net/)
```

2022-08-23 13:16 UTC, Aakrut commented
Updated!

2022-09-28 16:31 UTC, shahednasser approved these changes

2022-09-28 16:31 UTC, merged