Update README.md
shahednasser/awesome-resources pull request #422
Opened 2022-09-06 06:50 UTC by kartikver15gr8

Added a JavaScript Tutorial for Beginners to Advance😎

2022-09-28 16:47 UTC, shahednasser requested changes

2022-09-28 16:47 UTC, shahednasser commented on README.md
> +- :wrench: [JavaScript tutorial for Beginners😎](https://www.youtube.com/watch?v=lI1ae4REbFM&t=1s)
```suggestion
- : video_camera: [JavaScript tutorial for Beginners😎](https://www.youtube.com/watch?v=lI1ae4REbFM&t=1s)
```

2022-09-29 19:42 UTC, shahednasser commented on README.md
> +- :video_camera: [JavaScript tutorial for Beginners😎](https://www.youtube.com/watch?v=lI1ae4REbFM&t=1s)
```suggestion
- :video_camera: [JavaScript tutorial for Beginners 😎](https://www.youtube.com/watch?v=lI1ae4REbFM&t=1s)
```

2022-10-03 16:22 UTC, shahednasser approved these changes

2022-10-03 16:22 UTC, merged

2022-10-03 16:54 UTC, kartikver15gr8 commented
Your welcome @shahednasser 😊😊