feat: add regular expression category and resources
shahednasser/awesome-resources pull request #446
Opened 2022-10-01 14:23 UTC by savioxavier

Hello there! 👋

This pull request adds a new category to the list - Regular Expressions

I personally believe Regular Expressions (or regex, or regexp, call it whatever you will) are incredibly helpful for any programmer, so I've added this category.

I have also taken the liberty of adding a few relevant resources, including tools and short courses, under the same topic

Cheers!

2022-10-03 16:35 UTC, shahednasser requested changes
Thank you for your contribution! I added some comments below, but in addition I can see you made changes to all of the table of content. Can you just add a new link for Regular Expressions and revert all changes?

2022-10-03 16:35 UTC, shahednasser commented on README.md
> +## Regular Expressions
Please add before this the "Back to Index" link. Refer to the [contribution guidelines](https://github.com/shahednasser/awesome-resources/blob/master/CONTRIBUTING.md) for more details.

2022-10-04 10:53 UTC, savioxavier commented
No problemo, I'll fix those changes. It looks like my markdown formatter accidently updated the table of contents though.

2022-10-04 11:18 UTC, savioxavier commented
Unfortunately, I think I messed up the `git revert` (rookie mistake) and although I have fixed it in another remote branch, it's not possible to change the target branch now. I may need to open another pull request. I apologize for the inconvenience.

2022-10-04 11:18 UTC, closed without merging

2022-10-04 11:23 UTC, savioxavier commented
There we go. Please check out the new PR and let me know if there' anything left to be done. Thanks!