added Resources on multiple topics
shahednasser/awesome-resources pull request #475
Opened 2022-10-04 16:21 UTC by Tushar-2003

as mentioned in #1 ,
I have added resources for multiple topics -blockchain, DevOps, database, PostgreSQL, etc. 
let me know if there are any changes to be made :)

2022-10-04 17:43 UTC, shahednasser requested changes

2022-10-04 17:43 UTC, shahednasser commented on README.md
> +
Remove this line

2022-10-04 18:42 UTC, Tushar-2003 commented
@shahednasser done with the changes you asked for.

2022-10-05 17:29 UTC, shahednasser approved these changes

2022-10-05 17:29 UTC, merged