Kartikver15gr8 patch 1
shahednasser/awesome-resources pull request #476
Opened 2022-10-04 17:49 UTC by kartikver15gr8

2022-10-05 17:28 UTC, shahednasser requested changes

2022-10-05 17:28 UTC, shahednasser commented on README.md
> +
```suggestion

```

2022-10-05 17:28 UTC, shahednasser commented on README.md
> +- :video_camera: [Git & GitHub Tutorial For Beginners In Hindi - हिंदी में](https://www.youtube.com/watch?v=gwWKnnCMQ5c&t=2829s)
```suggestion
- :video_camera: [Git & GitHub Tutorial For Beginners In Hindi - हिंदी में](https://www.youtube.com/watch?v=gwWKnnCMQ5c)
```

2022-10-05 18:00 UTC, shahednasser commented on README.md
> -
Keep this empty line but without any spaces

2022-10-07 16:30 UTC, shahednasser commented on README.md
> -
Keep this line as well

2022-10-07 17:34 UTC, kartikver15gr8 commented
Is it good now

2022-10-11 18:54 UTC, shahednasser approved these changes

2022-10-11 18:54 UTC, merged

2022-10-11 18:54 UTC, shahednasser commented
Thanks! @kartikver15gr8