Added ThreeJS category
shahednasser/awesome-resources pull request #514
Opened 2022-10-07 06:05 UTC by ArnabDey1543

1. threejs official documentation
2.  threeJS tutorials by Bruno simon
3. free youtube courses by DesignCourse

2022-10-07 16:48 UTC, shahednasser requested changes
Thank you for your contribution. In addition to the comment I left below, please make sure you use the name "Three.js" in all headings, links, etc...

2022-10-07 16:48 UTC, shahednasser commented on README.md
> +- :video_camera: [ThreeJS Course: threeJs journey by Bruno Simon](https://threejs-journey.com/)
```suggestion
- :books: [Three.js Course: Three.js journey by Bruno Simon](https://threejs-journey.com/)
```

2022-10-08 19:11 UTC, ArnabDey1543 commented on README.md
> +- :video_camera: [ThreeJS Course: threeJs journey by Bruno Simon](https://threejs-journey.com/)
Sure, i'll make the changes

2022-10-08 19:22 UTC, ArnabDey1543 commented
Ma'am i've made the changes as you asked, will also try add some more top notch resources to Three.js category.
I am also thinking of adding AWS cloud category with services in subcategories.

2022-10-09 12:20 UTC, ArnabDey1543 commented
@shahednasser ma'am i have resolved all the issues, please consider my PR

2022-10-11 19:12 UTC, shahednasser requested changes

2022-10-11 19:12 UTC, shahednasser commented on README.md
> +- :video_camera: [Three.js Course: Three.js journey by Bruno Simon](https://threejs-journey.com/)
```suggestion
- :books: [Three.js Course: Three.js journey by Bruno Simon](https://threejs-journey.com/)
```

2023-09-21 20:52 UTC, closed without merging