added open ai gpt-3 machine learning documentation
shahednasser/awesome-resources pull request #526
Opened 2022-10-09 05:59 UTC by spencer1573

let me know if you have any questions or concerns. thanks!

2022-10-11 19:08 UTC, shahednasser requested changes

2022-10-11 19:08 UTC, shahednasser commented on README.md
> +- :file_folder: [Open AI GPT-3 Code completion: How to generate or manipulate code](https://beta.openai.com/docs/guides/code)
Please link instead to the main documentation page

2022-10-18 00:42 UTC, spencer1573 commented
Hey i got that changed! let me know if there is anything else. thanks!

2023-09-21 20:53 UTC, shahednasser approved these changes

2023-09-21 20:53 UTC, merged