new book has been added
shahednasser/awesome-resources pull request #540
Opened 2022-10-11 13:52 UTC by Deepshikhayadav

some new resourses

2022-10-11 19:23 UTC, shahednasser requested changes

2022-10-11 19:23 UTC, shahednasser commented on README.md
> +- :book: [Essential Dart](https://www.programming-books.io/essential/dart)
This page is not working.

2022-10-12 03:09 UTC, Deepshikhayadav commented on README.md
> +- :book: [Essential Dart](https://www.programming-books.io/essential/dart)
Now working plz do review

2023-09-21 20:54 UTC, shahednasser approved these changes

2023-09-21 20:54 UTC, merged