Updated ReadME
shahednasser/awesome-resources pull request #57
Opened 2020-10-01 12:32 UTC by amitkrishna

2020-10-01 12:34 UTC, shahednasser requested changes

2020-10-01 12:34 UTC, shahednasser commented on README.md
> +---
Please remove these horizontal lines

2020-10-01 12:34 UTC, shahednasser commented on README.md
> +---
Please remove these horizontal lines

2020-10-01 12:45 UTC, shahednasser commented
Please do not remove all the horizontal lines, just the ones I labeled.

2020-10-02 10:24 UTC, amitkrishna commented
Hi @shahednasser can u review this PR?

2020-10-02 11:26 UTC, merged

2020-10-02 11:27 UTC, shahednasser commented
thank you!